@base_url = http://localhost:4000
@bearer_token = Bearer Xlar77DzJgcpeXxnRkS9iw-cJguSwivSy5BuUTYh7q5
@client_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDU2NTM1MTcsImlhdCI6MTc0NTA0ODcxNywiaXNzIjoic2F0dXJkYXkiLCJzdWIiOiJ0b2tlbiIsIldobyI6Ijc4NiIsIk1lbWJlciI6eyJtZW1iZXJJZCI6IiIsImxvZ3RvSWQiOiIiLCJhbGlhcyI6IiIsIm5hbWUiOiIiLCJzZWN0aW9uIjoiIiwicm9sZSI6IiIsInByb2ZpbGUiOiIiLCJwaG9uZSI6IiIsInFxIjoiIiwiYXZhdGFyIjoiIiwiY3JlYXRlZEJ5IjoiIiwiZ2l0aHViSWQiOiIiLCJnbXRDcmVhdGUiOiIiLCJnbXRNb2RpZmllZCI6IiJ9LCJSb2xlIjoiY2xpZW50In0.ABKY6gkofhACCnoQX_83Z433KDgjfQAS59RnSxQ5kpQ

@logto_token = Bearer eyJhbGciOiJFUzM4NCIsInR5cCI6ImF0K2p3dCIsImtpZCI6IjdoVzQ5azFHaHA3TDVfc00td2E1eGQzck1YT1VXWkRWVUlZVlBSSXFIdjAifQ.eyJqdGkiOiJjQTdHRmw5OEJLUVo4WEtuNERZVnciLCJzdWIiOiJubnljcmozeTVzNDA5bGM2cDRzNmIiLCJpYXQiOjE3NDU1ODg5MjUsImV4cCI6MTc0NTU5MjUyNSwic2NvcGUiOiJhbGwiLCJjbGllbnRfaWQiOiJubnljcmozeTVzNDA5bGM2cDRzNmIiLCJpc3MiOiJodHRwczovL2F1dGguYXBwLm5idGNhLnNwYWNlL29pZGMiLCJhdWQiOiJodHRwczovL2RlZmF1bHQubG9ndG8uYXBwL2FwaSJ9.Nkj1Rk3JrGOjlfS4WCG4xvv0rnwXXypClo9qc9YcOVw3pJeAnvhEaVyj6_qH_vgHbHVdu4kUcYJzBiCNA2upkeF1ky-Y8VI0Ju3ArhqM78Dva7vwp4LrDzlESf1odc2h

###
@member_id = 2333333333

PATCH  {{base_url}}/members/{{member_id}}/logto_id
Authorization: {{bearer_token}}
Content-Type: application/json

{
  "password": "827ccb0eea8a706c4c34a16891f84e7b"
}

# ###
# POST  {{base_url}}/clients/token/wechat
# Content-Type: application/json

# {
#   "code": "081Zzq0009ZzqZ1z5zq00ZzqQq0ZzqQ1"
# }


###
POST  {{base_url}}/clients/token/logto
Content-Type: application/json
Authorization: {{bearer_token}}


### 

# Get client event
GET  {{base_url}}/client/events/379
Authorization: {{bearer_token}}

### 

# Create event
POST  {{base_url}}/client/event
Content-Type: application/json
Authorization: {{bearer_token}}

{
  "model": "iPhone 12",
  "phone": "13800138000",
  "qq": "123456",
  "contactPreference": "phone",
  "problem": "I have a problem with my phone"
}
###
# Update event by id
PATCH {{base_url}}/client/events/382
Content-Type: application/json
Authorization: {{bearer_token}}

{
  "model": "iPhone 16",
  "phone": "13800138000",
  "qq": "123456",
  "contactPreference": "phone",
  "problem": "I have a problem with my phone"
}

###
# Cancel event by id
DELETE {{base_url}}/client/events/382
Content-Type: application/json
Authorization: {{bearer_token}}

###

GET  {{base_url}}/events/376
Content-Type: application/json
Authorization: {{bearer_token}}

###
@eventId = 362
POST  {{base_url}}/events/{{eventId}}/close
Content-Type: application/json
Authorization: {{bearer_token}}


### 

POST https://dify-cloud.nbtca.space/v1/workflows/run
Authorization: Bearer app-iLgRRdmYRy8sj1AmQhqVHMuR
Content-Type: application/json

{
    "inputs": {
      "EventId": 9
    },
    "response_mode": "streaming",
    "user": "abc-123"
}


###
@connectorId = qkx6g4zo3ucufxkynou1r
POST https://auth.app.nbtca.space/api/connectors/{{connectorId}}/authorization-uri
Authorization: {{logto_token}}
Content-Type: application/json

{
  "redirectUri": "http://localhost:5173",
  "state": "randomstate"
}


###
GET  https://auth.app.nbtca.space/api/account-center
Authorization: {{logto_token}}

###
PATCH https://auth.app.nbtca.space/api/account-center
Authorization: {{logto_token}}
Content-Type: application/json

{
  "enabled":true,
  "fields": {
    "name": "Edit",
    "avatar": "Edit",
    "profile": "Edit",
    "email": "Edit",
    "phone": "Edit",
    "password": "Edit",
    "username": "Edit",
    "social": "Edit",
    "customData": "Edit"
  }
}
###
GET http://localhost:4000/events/xlsx?start_time=2025-01-01T00:00:00Z&end_time=2025-05-31T23:59:59Z
Authorization: {{bearer_token}}


### 

# PATCH http://localhost:4000/members/2333333333
PATCH https://repair.nbtca.space/api/members/3230515066
Authorization: Bearer gZO9brxC6nrMmQY220wHOnuhr81GJVL7aK9pgi3LmjX
Content-Type: application/json

{
  "role":"admin"
}
